main_admin:
    resource: "@MainAdminBundle/Resources/config/routing.yml"
    prefix:   /

main_common:
    resource: "@MainCommonBundle/Resources/config/routing.yml"
    prefix:   /

main_frontend:
    resource: "@MainFrontendBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @MainFrontendBundle/Controller/
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
