services:
    split_file:
        class: Main\CommonBundle\Services\SplitFile
        arguments:
            - @old_sound_rabbit_mq.split_file_producer
    process_node:
        class: Main\CommonBundle\Services\ReadNode
        arguments:
            - @doctrine.orm.entity_manager
            - @snc_redis.default
            - @service_container
    soldier_data:
        class: Main\CommonBundle\Services\SoldierData
        arguments:
            - @doctrine.orm.entity_manager
            - @snc_redis.default
            - @service_container
