services:
    soldier_queue:
        class: Main\CommonBundle\Services\SoldierQueue
        arguments:
            - @old_sound_rabbit_mq.soldier_queue_producer
    building_queue:
        class: Main\CommonBundle\Services\SoldierQueue
        arguments:
            - @old_sound_rabbit_mq.soldier_queue_producer
    save_soldiers:
        class: Main\CommonBundle\Services\SaveSoldiers
        arguments:
            - @doctrine.orm.entity_manager
            - @snc_redis.default
            - @service_container
    save_building:
        class: Main\CommonBundle\Services\SaveSoldiers
        arguments:
            - @doctrine.orm.entity_manager
            - @snc_redis.default
            - @service_container
    soldier_data:
        class: Main\CommonBundle\Services\SoldierData
        arguments:
            - @doctrine.orm.entity_manager
            - @snc_redis.default
            - @service_container
    spy_service:
        class: Main\CommonBundle\Services\SpyService
        arguments:
            - @doctrine.orm.entity_manager
            - @snc_redis.default
            - @service_container
    points_service:
        class: Main\CommonBundle\Services\PointsService
        arguments:
            - @snc_redis.default
            - @service_container
