services:
    soldier_queue:
        class: Main\CommonBundle\Services\SoldierQueue
        arguments:
            - @old_sound_rabbit_mq.soldier_queue_producer
    process_node:
        class: Main\CommonBundle\Services\ReadNode
        arguments:
            - @doctrine.orm.entity_manager
            - @snc_redis.default
            - @service_container
    soldier_data:
        class: Main\CommonBundle\Services\SoldierData
        arguments:
            - @doctrine.orm.entity_manager
            - @snc_redis.default
            - @service_container
