frontend.view.map:
    path:     /map
    defaults: { _controller: MainFrontendBundle:Map:show }

frontend.API.map.users:
    path:     /map/users
    defaults: { _controller: MainFrontendBundle:Map:mapUsers }
    methods: [GET]

frontend.API.map.user.data:
    path:     /map/user/{id}
    defaults: { _controller: MainFrontendBundle:Map:userData }
    methods: [GET]