frontend.view.homepage:
    path:     /
    defaults: { _controller: MainFrontendBundle:Default:index }

frontend.view.soldiers:
    path:     /soldiers
    defaults: { _controller: MainFrontendBundle:Soldiers:show }

frontend.view.vehicles:
    path:     /vehicles
    defaults: { _controller: MainFrontendBundle:Vehicles:show }

frontend.view.buildings:
    path:     /buildings
    defaults: { _controller: MainFrontendBundle:Buildings:show }

frontend.API.soldiers:
    path: /soldiers/data
    defaults: { _controller: MainFrontendBundle:Soldiers:data }
    methods: [GET]

frontend.API.add_soldier_to_queue:
    path: /soldiers/queue
    defaults: { _controller: MainFrontendBundle:Soldiers:addSoldierToQueue }
    methods: [POST]

frontend.API.get_points:
    path: /points
    defaults: { _controller: MainFrontendBundle:Points:get }
    methods: [GET]

map:
    resource: "@MainFrontendBundle/Resources/config/map.yml"
