main_frontend_homepage:
    path:     /
    defaults: { _controller: MainFrontendBundle:Default:index }

frontend.get_points:
    path: /points
    defaults: { _controller: MainFrontendBundle:Points:get }
    methods: [GET]