frontend.view.homepage:
    path:     /
    defaults: { _controller: MainFrontendBundle:Default:index }

frontend.view.soldiers:
    path:     /soldiers
    defaults: { _controller: MainFrontendBundle:Soldiers:show }

frontend.rest.get_points:
    path: /points
    defaults: { _controller: MainFrontendBundle:Points:get }
    methods: [GET]

