assetic:
    assets:
        bootstrap_css:
            inputs:
                - '%kernel.root_dir%/../bower_components/bootstrap/dist/css/bootstrap.css'
        frontend_css:
            inputs:
                - '%kernel.root_dir%/../src/Main/FrontendBundle/Resources/public/css/main.css'
        angular_aside_css:
            inputs:
                - '%kernel.root_dir%/../bower_components/angular-aside/dist/css/angular-aside.css'
