assetic:
    assets:
        jquery_js:
            inputs:
                - '%kernel.root_dir%/../bower_components/jquery/dist/jquery.js'
        angular_js:
            inputs:
                - '%kernel.root_dir%/../bower_components/angular/angular.js'
        angular_route_js:
            inputs:
                - '%kernel.root_dir%/../bower_components/angular-route/angular-route.js'
        moment_js:
            inputs:
                - '%kernel.root_dir%/../bower_components/moment/moment.js'
        angular_bootstrap_js:
            inputs:
                - '%kernel.root_dir%/../bower_components/angular-bootstrap/ui-bootstrap.js'
                - '%kernel.root_dir%/../bower_components/angular-bootstrap/ui-bootstrap-tpls.js'
        angular_aside_js:
            inputs:
                - '%kernel.root_dir%/../bower_components/angular-aside/dist/js/angular-aside.js'
        angular_timer_js:
            inputs:
                - '%kernel.root_dir%/../bower_components/angular-timer/dist/angular-timer.js'
        firebase_js:
            inputs:
                - '%kernel.root_dir%/../bower_components/firebase/firebase.js'
                - '%kernel.root_dir%/../bower_components/angularfire/dist/angularfire.js'
        ngcsv_js:
            inputs:
                - '%kernel.root_dir%/../bower_components/ng-csv/build/ng-csv.min.js'
        ngsanitize_js:
            inputs:
                - '%kernel.root_dir%/../bower_components/angular-sanitize/angular-sanitize.js'
        d3_js:
            inputs:
                - '%kernel.root_dir%/../bower_components/d3/d3.js'
        frontend_js:
            inputs:
               - '@MainFrontendBundle/Resources/public/js/*'
               - '@MainFrontendBundle/Resources/public/js/*/*'
               - '@MainFrontendBundle/Resources/public/js/*/*/*'
        admin_js:
            inputs:
               - '@MainAdminBundle/Resources/public/js/*'
               - '@MainAdminBundle/Resources/public/js/*/*'
               - '@MainAdminBundle/Resources/public/js/*/*/*'