assetic:
    assets:
        jquery_js:
            inputs:
                - '%kernel.root_dir%/../bower_components/jquery/dist/jquery.js'
        angular_js:
            inputs:
                - '%kernel.root_dir%/../bower_components/angular/angular.js'
#        frontend_js:
#            inputs:
#               - '@MainFrontendBundle/Resources/public/js/*'
#               - '@MainFrontendBundle/Resources/public/js/*/*'